### ISSUE TITLE
No License for this project

### ISSUE THREAD

**Issue by badboywj** [pbrezina/pam-test#1]
I plan to package this project, but notice that no license for this project,
Could I get the authorization? or please add a license.

**Comment by pbrezina** [comment]
Why and where do you want to package it? This is just sample application.

**Comment by badboywj** [comment]
It will be used for testing PAM in our company, I find your project and it is smart and its function is enough, but no license, so I try to ping you, I want to know if I can get your authorization.

**Comment by pbrezina** [comment]
Ok, I added a license information. I'm glad it finds some use cases, but please note that I am not even sure if it works correctly. It served for me just to get familiar with PAM clients and it wasn't meant to find wider audience. Anyway, pull requests to fix issues are welcomed.

**Comment by badboywj** [comment]
> Ok, I added a license information. I'm glad it finds some use cases, but please note that I am not even sure if it works correctly. It served for me just to get familiar with PAM clients and it wasn't meant to find wider audience. Anyway, pull requests to fix issues are welcomed.

Thank you : )
